### ISSUE TITLE
Question of the Router position in Dateset

### ISSUE THREAD

**Issue by Awaker1** [wenhaol/DCM-RSSI#1]
Hi, thanks for your dataset of RSSI, but I'm curious about the Router position in the dataset. You mentioned that Router position is encoded in Router_{Column}{Raw}.txt, but I cannot get the exact xy coordinates of each router to train the GP model. Did I ignore part of the instructions?

**Comment by yupengyanguncc** [comment]
Hi, thank you for helping us identify this issue. To assist further, we will provide the following document [route_info.csv](https://github.com/user-attachments/files/17510868/route_info.csv) to record the router information. Should you have any additional questions, please don't hesitate to reach out. I am happy to assist you further.  
<img src="https://github.com/user-attachments/assets/158e100c-6ac9-42a9-911b-45e526ea7e21" width="300" height="300" />
